trigger:
  branches:
    include:
    - releases/*

# Disable PullRequest Validation
pr: none

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self
  persistCredentials: true
  clean: true

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Install-PackageProvider -Name NuGet -Force -Scope CurrentUser
      Install-Module -Name PoShLog.Tools -Force -Verbose -Scope CurrentUser
      Import-Module -Name PoShLog.Tools
      Bootstrap '.\cd\RequiredModules.psd1'